name: docker-vllm-npu

on:
  workflow_dispatch:  
  push:
    branches: [ "*" ] 
    paths:
      - "**/*.py"
      - "requirements.txt"
      - "docker/Dockerfile.ascend_vllm-0.9.1"  
      - ".github/workflows/docker-verl-npu.yml" 
  pull_request:
    branches: [ "main" ]
    paths:  
      - "**/*.py"
      - "requirements.txt"
      - "docker/Dockerfile.ascend_vllm-0.9.1"
      - ".github/workflows/docker-verl-npu.yml"
  release:
    types: [ published ] 
  schedule:
    - cron: "0 16 * * *"  # UTC时间16点 = 北京时间0点，仅更新main分支

jobs:
  build-vllm-npu:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-vllm-npu
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          docker-images: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Get image tag
        id: version
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///g' | sed 's/[^a-zA-Z0-9._-]/_/g')
          
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}-a2-py11" >> "$GITHUB_OUTPUT"
          elif [ "$BRANCH_NAME" = "main" ]; then
            echo "tag=latest-a2-py11" >> "$GITHUB_OUTPUT"
          else
            echo "tag=branch-${BRANCH_NAME}-a2-py11" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: crpi-nc9mglthamj2w1bt.cn-hangzhou.personal.cr.aliyuncs.com
          username: ssy709222099
          password: ${{ secrets.ALIYUN_CR_PASSWORD }} 

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push images (Quay + Aliyun)
        uses: docker/build-push-action@v6
        with:
          context: .  
          platforms: linux/amd64,linux/arm64 
          file: ./docker/Dockerfile.ascend_vllm-0.9.1  
          push: true 
          tags: |  
            crpi-nc9mglthamj2w1bt.cn-hangzhou.personal.cr.aliyuncs.com/ascend_linke/verl_x86:${{ steps.version.outputs.tag }}
            quay.io/709222099/verl:${{ steps.version.outputs.tag }}
          cache-from: type=gha  
          cache-to: type=gha,mode=max  
